# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SFS_ACCOUNT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='メールアドレス')),
                ('user_name', models.CharField(max_length=100, verbose_name='ユーザー名')),
                ('apply_begin', models.DateField(default=django.utils.timezone.now, verbose_name='適用開始日')),
                ('apply_end', models.DateField(default='9999-12-31', verbose_name='適用開始日')),
                ('create_date', models.DateField(default=django.utils.timezone.now, verbose_name='作成日')),
            ],
            options={
                'db_table': 'm_account',
            },
        ),
        migrations.CreateModel(
            name='SFS_MANAGERMSG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('create_user', models.CharField(max_length=100, verbose_name='作成者')),
                ('create_date', models.DateField(default=django.utils.timezone.now, verbose_name='作成日')),
            ],
            options={
                'db_table': 'm_managermsg',
            },
        ),
        migrations.CreateModel(
            name='SFS_NOTICE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='お知らせ内容')),
                ('user', models.CharField(max_length=100, verbose_name='作成者')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='お知らせ日')),
            ],
            options={
                'db_table': 'm_notice',
            },
        ),
    ]
