# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SfsAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='メールアドレス')),
                ('user_name', models.CharField(max_length=100, verbose_name='ユーザー名')),
                ('apply_begin', models.DateField(default=django.utils.timezone.now, verbose_name='適用開始日')),
                ('apply_end', models.DateField(default='9999-12-31', verbose_name='適用開始日')),
                ('create_date', models.DateField(default=django.utils.timezone.now, verbose_name='作成日')),
            ],
            options={
                'verbose_name': 'アカウント',
                'verbose_name_plural': '業務 : アカウント (m_account)',
                'db_table': 'm_account',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SfsBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('apply_begin', models.DateField(verbose_name='適用開始日')),
                ('apply_end', models.DateField(verbose_name='適用終了日')),
                ('create_user', models.CharField(max_length=100, verbose_name='作成者')),
                ('create_date', models.DateField(default=django.utils.timezone.now, verbose_name='作成日')),
            ],
            options={
                'verbose_name': '業務',
                'verbose_name_plural': '業務 : 業務 (m_business)',
                'db_table': 'm_business',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SfsCaption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='コード')),
                ('title_jp', models.CharField(max_length=100, verbose_name='名称(ja)')),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='名称(en)')),
                ('title_th', models.CharField(blank=True, max_length=100, null=True, verbose_name='名称(th)')),
                ('page_id', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='画面ID')),
            ],
            options={
                'verbose_name': '項目タイトル',
                'verbose_name_plural': '業務 : 項目タイトル (m_caption)',
                'db_table': 'm_caption',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SfsCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_cd', models.CharField(max_length=100, verbose_name='企業コード')),
                ('company_name', models.CharField(max_length=100, verbose_name='企業名称')),
                ('money', models.CharField(max_length=100, verbose_name='資本金')),
                ('create_date', models.DateField(default=django.utils.timezone.now, verbose_name='成立日')),
                ('manager_name', models.CharField(max_length=100, verbose_name='代表取締役')),
                ('sub_manager_name', models.CharField(max_length=100, verbose_name='取締役')),
                ('address', models.CharField(max_length=255, verbose_name='住所')),
                ('email', models.EmailField(max_length=100, verbose_name='メールアドレス')),
                ('telphone', models.CharField(max_length=20, verbose_name='電話')),
            ],
            options={
                'verbose_name': '企業',
                'verbose_name_plural': '業務 : 企業 (m_company)',
                'db_table': 'm_company',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SfsEmployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('apply_begin', models.DateField(verbose_name='適用開始日')),
                ('apply_end', models.DateField(verbose_name='適用終了日')),
                ('create_user', models.CharField(max_length=100, verbose_name='作成者')),
                ('create_date', models.DateField(default=django.utils.timezone.now, verbose_name='作成日')),
            ],
            options={
                'verbose_name': '採用',
                'verbose_name_plural': '業務 : 採用 (m_employment)',
                'db_table': 'm_employment',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SfsIdea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('apply_begin', models.DateField(verbose_name='適用開始日')),
                ('apply_end', models.DateField(verbose_name='適用終了日')),
                ('create_user', models.CharField(max_length=100, verbose_name='作成者')),
                ('create_date', models.DateField(default=django.utils.timezone.now, verbose_name='作成日')),
            ],
            options={
                'verbose_name': '理念',
                'verbose_name_plural': '業務 : 理念 (m_idea)',
                'db_table': 'm_idea',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SfsManagermsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('apply_begin', models.DateField(verbose_name='適用開始日')),
                ('apply_end', models.DateField(verbose_name='適用終了日')),
                ('create_user', models.CharField(max_length=100, verbose_name='作成者')),
                ('create_date', models.DateField(default=django.utils.timezone.now, verbose_name='作成日')),
            ],
            options={
                'verbose_name': '管理者のメッセージ',
                'verbose_name_plural': '業務 : 管理者のメッセージ (m_managermsg)',
                'db_table': 'm_managermsg',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SfsTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='トッピク内容')),
                ('apply_begin', models.DateField(default=django.utils.timezone.now, verbose_name='適用開始日')),
                ('create_user', models.CharField(max_length=100, verbose_name='作成者')),
                ('create_date', models.DateField(default=django.utils.timezone.now, verbose_name='作成日')),
            ],
            options={
                'verbose_name': 'トッピク',
                'verbose_name_plural': '業務 : トッピク (m_topic)',
                'db_table': 'm_topic',
                'ordering': ['-id'],
            },
        ),
    ]
